### PR TITLE
Add CaseSensitive Flag, to allow search with Case or ignore Case

### PR DESCRIPTION
**Pull request by Alexplose**
When you receive the DataRequest on the controller you can change this flag to allow CaseSensitive or CaseInsensitive filtering

### CODE REVIEW

**Comment by Alexplose** [comment]
@ekondur can you please check and merge I need this :)

**Comment by ekondur** [comment]
Hi @Alexplose, 
Thanks for your contribution, if it will have a case-sensitive option, should have selectable on the UI as well, 
I have another idea for it, I think it should be insensitive by default because if you are sending the query to the database you are already using insensitive, this feature should also apply to server-side retrieving. wdyt?

**Comment by Alexplose** [comment]
Hi,
Yes that's what I wanted to do, have a default case insensitive search or
filtering by default, but didn't want to make a breaking change for those
that use it already and are happy with it the way it works now.
I don't need it on the ui, but it could be useful to define it via the
datatable helper.

**Comment by ekondur** [comment]
Hi @Alexplose 
I think it's okay to be insensitive by default, can you update it that way, please?

**Comment by Alexplose** [comment]
Hey, 

Is the case, the : `public bool CaseSensitive { get;  set; }` will have a default value to false.
So you can merge :)

**Comment by ekondur** [comment]
Hi @Alexplose 
There was an issue and fixed #126 
Released with 3.7.0 package.
Thank you!

**Pull request merged**
